# Based on https://github.com/im85288/service.upnext/blob/master/.github/workflows/release.yml
name: Make Release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'
      - '*-dev'
env:
  ADDON_REPOSITORY_URL: codingPF/repository.codingPF
  ADDON_REPOSITORY_NAME: repository.codingPF


jobs:
  release:
    if: github.repository == 'codingPF/plugin.video.newsApp' || github.event_name == 'workflow_dispatch'
    name: Make Release
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - name: Release Status
        id: release
        run: |
          version=${GITHUB_REF/refs\/tags\//}
          if [[ $version == *-dev ]] ;
          then
            echo "pre-release=true" >> $GITHUB_OUTPUT
          else
            echo "pre-release=false" >> $GITHUB_OUTPUT
          fi

      # source repo
      - name: Checkout Add-on
        uses: actions/checkout@v3
        with:
          path: ${{ github.event.repository.name }}

      # repository repo
      - name: Checkout Add-on
        uses: actions/checkout@v3
        with:
          repository: '$ADDON_REPOSITORY_URL'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils xmlstarlet zip

      - name: Get Changelog
        id: changelog
        run: |
          readarray -t changes < <(xmlstarlet sel -t -v '//news' -n addon.xml)
          echo "body<<${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
          for change in "${changes[@]}"; do
              echo "${change}" >> $GITHUB_OUTPUT
          done
          echo "${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_OUTPUT
        working-directory: ${{ github.event.repository.name }}

      - name: Create Zip (Nexus)
        id: zip-nexus
        run: |
          mv .git ..
          rm -rf .??*
          rm *.md
          version=$(xmlstarlet sel -t -v 'string(/addon/@version)' addon.xml)
          filename=${{ github.event.repository.name }}-${version}.zip
          cd ..
          zip -r $filename ${{ github.event.repository.name }}
          mv .git ${{ github.event.repository.name }}
          echo "filename=$filename" >> $GITHUB_OUTPUT
        working-directory: ${{ github.event.repository.name }}

      - name: Update Target Repository (Nexus)
        id: update-nexus-repository
        run: |
          cp ${{ github.event.repository.name }} ADDON_REPOSITORY_NAME/leia/zips/${{ github.event.repository.name }}/
        working-directory: ${{ github.event.repository.name }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

